name: Tag from changelog

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # nécessaire pour voir les tags

      - name: Detect version in changelog
        id: ver
        run: |
          # extrait la première version du changelog (vX.Y.Z)
          VERSION=$(grep -m1 -E '^##[[:space:]]+v[0-9]+\.[0-9]+\.[0-9]+' changelog.md | sed -E 's/^##[[:space:]]+//')
          if [ -z "$VERSION" ]; then
            echo "No version found in changelog.md"
            echo "found=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "found=true" >> $GITHUB_OUTPUT
          echo "Found version: $VERSION"

      - name: Check if tag already exists
        if: steps.ver.outputs.found == 'true'
        id: exists
        run: |
          TAG="${{ steps.ver.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag already exists: $TAG"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.ver.outputs.found == 'true' && steps.exists.outputs.exists == 'false'
        run: |
          TAG="${{ steps.ver.outputs.version }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"
